name: Validate JSON Schemas

on:
  push:
    branches:
      - '**'

jobs:
  validate-schemas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install jv
      run: |
        go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Validate JSON schemas
      run: |
        for file in $(find . -name "*.schema.json"); do
          echo "Validating $file"
          jv $file
        done
