name: Validate JSON Schemas

on:
  push:
    branches:
      - '**'

jobs:
  validate-schemas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate JSON schemas
      uses: docker://orrosenblatt/validate-json-action:latest
      env:
        INPUT_SCHEMA: |
          $(find $(pwd) -name "*.schema.json" | tr '\n' ',')
        INPUT_JSONS: |
          $(find $(pwd) -name "*.json" ! -name "*.schema.json" | tr '\n' ',')
