name: Validate JSON Schemas

on:
  push:
    branches:
      - '**'

jobs:
  validate-schemas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate JSON schemas
      uses: OrRosenblatt/validate-json-action@v1
      with:
        schemas: '**/*.schema.json'
